Restore reactor.iterate in dht shutdown
This reverts the change made in 693fef1964e281eaf7b39f9bd9f5728406942a14

Not sure why this is needed, but taking this out sometimes causes
`exceptions.AttributeError: 'Port' object has no attribute 'socket'`
to happen on shutdown.