file_manager: handle the response better when a claim is not found
When using `lbrynet get URL`, if the URL does not exist
it will raise a `ResolveError` exception which will produce
a long backtrace.

For example
```
lbrynet get Non-existing
```

```
Traceback (most recent call last):
  File "/opt/git/lbry-sdk/lbry/file/file_manager.py", line 107, in download_from_uri
    raise ResolveError(f"Failed to resolve stream at '{uri}': {txo}")
lbry.error.ResolveError: Failed to resolve 'Failed to resolve stream at 'Non-existing':
{'error': {'name': 'NOT_FOUND', 'text': 'Could not find claim at "Non-existing".'}}'.
WARNING  lbry.extras.daemon.daemon:1106: Error downloading Non-existing:
Failed to resolve 'Failed to resolve stream at 'Non-existing':
{'error': {'name': 'NOT_FOUND', 'text': 'Could not find claim at "Non-existing".'}}'.
```

Not only that, the error message has a nested message inside so the full output
is quite ugly.

-------------------------------------------------------------------

Now we will search for the `'error'` key in the response. If it is,
and the `'text'` key is also present, we will raise `ResolveError`
with the message stored in this text.

We will trap `ResolveError` so that the entire trace is not printed.

```
WARNING  lbry.file.file_manager:251: Failed to download Non-existing:
Failed to resolve 'Could not find claim at "Non-existing".'.
WARNING  lbry.extras.daemon.daemon:1106: Error downloading Non-existing:
Failed to resolve 'Could not find claim at "Non-existing".'.
```